name: Golang CI Lint
# This workflow will run the golangci-lint analysis

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.x

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
